### ISSUE TITLE
NullPointerException when using disableLocation on Android

### ISSUE THREAD

**Issue by peterkuiper** [Countly/countly-sdk-react-native-bridge#54]
Here is part of the stacktrace:

```
NullPointerException: Attempt to invoke virtual method 'void ly.count.android.sdk.ModuleLocation$Location.disableLocation()' on a null object reference
    at ly.count.android.sdk.Countly.disableLocation(Countly.java:1125)
    at ly.count.android.sdk.react.CountlyReactNative.disableLocation(CountlyReactNative.java:324)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
...
(7 additional frame(s) were not displayed)
```

When I remove `Countly.disableLocation();` it works on Android. I don't have any problems on iOS.

I am using version `20.11.5`.

**Comment by ijunaid** [comment]
Hi @peterkuiper,
Thanks for reporting this issue. This call should be also working before init, but a recent release broke that.
We will add the fix of this issue in the next release.
For now we would recommend that you call `Countly.disableLocation();` after `Countly.init(...)`.

**Comment by ArtursKadikis** [comment]
Hello, this should already have been fixed
